import { fetchMarineBulletinHtml } from "./api/marineBulletin.js"; import { parseMarineBulletinHtml, renderMarineBulletinHtml } from "./popup/marineBulletinParser.js"; const MARINE_BULLETIN_PAGE_URL = "https://www.ilmatieteenlaitos.fi/saatiedotus-merenkulkijoille"; const MARINE_BULLETIN_REFRESH_MS = 60 * 60 * 1000;   function setupPanel(panelEl, { onFirstOpen } = {}) { const header = panelEl.querySelector(".info-panel-header"); if (!header) return; let loaded = false; header.addEventListener("click", () => { const isOpen = panelEl.classList.toggle("open"); header.setAttribute("aria-expanded", isOpen ? "true" : "false"); if (isOpen && !loaded) { loaded = true; onFirstOpen?.(); } }); } function renderMarineBulletinError(contentEl, message) { contentEl.innerHTML = `
    <div class="info-panel-error">
      ${message}
      <br>
      <a href="${MARINE_BULLETIN_PAGE_URL}" target="_blank" rel="noopener">
        Avaa säätiedotus ilmatieteenlaitos.fi:ssä ↗
      </a>
    </div>
  `; } async function loadMarineBulletin(contentEl, { showLoading = true } = {}) { if (showLoading) { contentEl.innerHTML = `<div class="info-panel-loading">Ladataan…</div>`; } try { const html = await fetchMarineBulletinHtml(); const bulletin = parseMarineBulletinHtml(html); contentEl.innerHTML = renderMarineBulletinHtml(bulletin); } catch (err) { console.warn("Säätiedotuksen haku epäonnistui:", err); renderMarineBulletinError( contentEl, "Säätiedotuksen haku ei onnistunut juuri nyt." ); } } export function initMarineInfoPanels() { const marinePanel = document.getElementById("marine-bulletin-panel"); if (marinePanel) { const contentEl = marinePanel.querySelector(".marine-bulletin-content"); setupPanel(marinePanel, { onFirstOpen: () => { loadMarineBulletin(contentEl);     setInterval( () => loadMarineBulletin(contentEl, { showLoading: false }), MARINE_BULLETIN_REFRESH_MS ); } }); } }
